project:
  type: website
  output-dir: docs

website:
  title: "Alex Sheridan"
  # navbar:
  #   left:
  #     - text: Home
  #       href: index.qmd
      # - text: More books
      #   href: books.qmd

        
format:
  html:
    mainfont: sans-serif
    fontsize: 1em
    theme: litera
    css: styles.css
    toc: true

editor: visual
